# Generated by Django 4.2.17 on 2024-12-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kondisi',
            field=models.CharField(choices=[('baru panen', 'Baru Panen'), ('segar', 'Segar'), ('kering', 'Kering')], default='baru panen', max_length=50),
        ),
    ]
